# Generated by Django 5.1 on 2024-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='rewards_for_completion',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
