# Generated by Django 5.1 on 2024-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_rewards_for_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='rewards_for_completion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
